### ISSUE TITLE
Remove deleteme line

### ISSUE THREAD

**Issue by skippernl** [drewhjelm/firewall-audit#3]
#write all the rules to the CSV for a VDOM and get ready for the next VDOM
    if (($line.Trim() -match "^end") -and ($policySection)) {
        $policySection = $false;
        $date = Get-Date -Format yyyyMMddhhmmss
        $ruleList = $ruleList | Select-Object -Skip 1
        if($utf8)

If you add -> $ruleList = $ruleList | Select-Object -Skip 1 <- the deleteme line is automaticly deleted before the export

**Comment by drewhjelm** [comment]
Thanks @skippernl. I pushed this change in:

https://github.com/drewhjelm/firewall-audit/commit/901f1dd31fddc427adf4758336c725a92f125f56
